# Generated by Django 5.1.1 on 2024-10-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cnic',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
    ]
