# Generated by Django 5.1.1 on 2024-10-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customer_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cnic',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
