# Generated by Django 5.1.1 on 2024-10-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic_no', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('residential_address', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.IntegerField(blank=True, null=True)),
                ('office_address', models.CharField(blank=True, max_length=250, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(max_length=100)),
                ('home_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor2_cnic_no', models.CharField(blank=True, max_length=15, null=True)),
                ('guarantor2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor2_father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor2_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor2_residential_address', models.CharField(blank=True, max_length=255, null=True)),
                ('guarantor2_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor2_monthly_income', models.IntegerField(blank=True, null=True)),
                ('guarantor2_office_address', models.CharField(blank=True, max_length=250, null=True)),
                ('guarantor2_office_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor2_phone_no', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor2_home_phone', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
