# Generated by Django 5.1.1 on 2024-10-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_guarantor_cnic_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantor',
            name='guarantor2_home_phone',
        ),
        migrations.RemoveField(
            model_name='guarantor',
            name='home_phone',
        ),
    ]
