# Generated by Django 5.1.1 on 2024-10-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_guarantor_guarantor2_cnic_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='cnic_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
