# Generated by Django 5.1.1 on 2024-10-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='product',
            name='down_payment_12_months',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='product',
            name='down_payment_3_months',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='product',
            name='down_payment_6_months',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='product',
            name='down_payment_9_months',
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name='product',
            name='fee_12_months',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='product',
            name='fee_3_months',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='product',
            name='fee_6_months',
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name='product',
            name='fee_9_months',
            field=models.FloatField(default=20.0),
        ),
    ]
