# Generated by Django 5.1.1 on 2024-10-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_installmentpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='installment_plan',
            field=models.CharField(choices=[('3_months', '3 Months Plan'), ('6_months', '6 Months Plan'), ('9_months', '9 Months Plan'), ('12_months', '12 Months Plan')], default=None, max_length=30),
        ),
    ]
