# Generated by Django 5.1.1 on 2024-10-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_delete_installmentplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentpayment',
            name='initial_amount_due',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
