# Generated by Django 5.1.1 on 2024-10-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_installmentpayment_initial_amount_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installment_status',
            field=models.TextField(blank=True, default=''),
        ),
    ]
