# Generated by Django 5.1.1 on 2024-10-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_installmentpayment_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
