# Generated by Django 5.1.1 on 2024-10-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_downpayment_installment_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downpayment',
            name='installment_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
