# Generated by Django 5.1.1 on 2024-10-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Sales Team'},
        ),
    ]
