# Generated by Django 5.1.1 on 2024-10-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_installment_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='installment_type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
