# Generated by Django 5.1.1 on 2024-10-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_installment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='payment_type',
            field=models.CharField(choices=[('installment', 'Installment'), ('cash', 'Cash')], default='installment', max_length=20),
        ),
    ]