# Generated by Django 5.1.1 on 2024-10-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_installment_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='installment_plan',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='installment_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
