# Generated by Django 5.1.1 on 2024-10-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_installment_plan_and_more'),
        ('products', '0009_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemDynamicInstallments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('installment_plan', models.CharField(blank=True, max_length=50, null=True)),
                ('monthly_payment', models.CharField(max_length=50)),
                ('total_amount', models.CharField(max_length=50)),
                ('down_payment', models.CharField(max_length=50)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dynamic_items', to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
