# Generated by Django 5.1.1 on 2024-10-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitemdynamicinstallments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='installment_type',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='CartItemDynamicInstallments',
        ),
    ]
