# Generated by Django 5.1.1 on 2024-10-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_installment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='installment_type',
            field=models.CharField(max_length=100),
        ),
    ]
