# Generated by Django 5.1.1 on 2024-10-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_installment_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstallmentPlan',
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='initial_amount_due',
            field=models.DecimalField(decimal_places=2, default=None, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Installment', 'Installment Payment')], max_length=30),
        ),
    ]
