# Generated by Django 5.1.1 on 2024-10-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_rename_installment_fee_downpayment_installment_form_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='installment_plan',
            field=models.CharField(choices=[('3_months', '3 Months Plan'), ('6_months', '6 Months Plan'), ('9_months', '9 Months Plan'), ('12_months', '12 Months Plan')], default='3_months', max_length=30),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='amount_due',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
