# Generated by Django 5.1.1 on 2024-10-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_orderitem_installment_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='installment_plan',
        ),
    ]
