# Generated by Django 5.1.1 on 2024-10-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_remove_orderitem_installment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installment_type',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='installment_plan',
            field=models.CharField(choices=[('1_months', '1 Months Plan'), ('2_months', '2 Months Plan'), ('3_months', '3 Months Plan'), ('4_months', '4 Months Plan'), ('5_months', '5 Months Plan'), ('6_months', '6 Months Plan'), ('7_months', '7 Months Plan'), ('8_months', '8 Months Plan'), ('9_months', '9 Months Plan'), ('10_months', '10 Months Plan'), ('11_months', '11 Months Plan'), ('12_months', '12 Months Plan')], default=None, max_length=30),
        ),
    ]
