# Generated by Django 5.1.1 on 2024-10-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_installment_type_alter_order_installment_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total_downpayment_price',
        ),
        migrations.AddField(
            model_name='order',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='installment_plan',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Every Month', 'Installment Payment')], max_length=30),
        ),
    ]
