# Generated by Django 5.1.1 on 2024-10-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_rename_total_price_order_total_downpayment_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
