# Generated by Django 5.1.1 on 2024-10-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_rename_total_downpayment_price_order_downpayment_plus_form_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='installment_total_price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='original_price',
        ),
    ]
