# Generated by Django 5.1.1 on 2024-10-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_rename_price_orderitem_installment_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='balance_amout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
