# Generated by Django 5.1.1 on 2024-10-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_installmentpayment_balance_amout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentpayment',
            name='balance_amout',
        ),
    ]
