# Generated by Django 5.1.1 on 2025-04-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_remove_order_guarantor_order_guarantors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Every Month', 'Every Month'), ('Cash', 'Cash')], max_length=30),
        ),
    ]
