# Generated by Django 5.1.1 on 2025-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
