# Generated by Django 5.1.1 on 2024-10-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
