# Generated by Django 5.1.1 on 2024-11-11 16:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='products_category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='products_images'),
        ),
    ]
