# Generated by Django 5.1.1 on 2024-11-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_photo_alter_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='slug',
        ),
    ]
