# Generated by Django 5.1.1 on 2024-11-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_slug1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='name',
        ),
    ]
