# Generated by Django 5.1.1 on 2024-11-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_slug_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug1',
            new_name='slug',
        ),
    ]
