# Generated by Django 5.1.1 on 2025-04-22 14:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_fee',
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='products_category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='products_images'),
        ),
    ]
